name: streamlit-docker-deployment
services:
- dockerfile_path: Dockerfile
  github:
    branch: main
    deploy_on_push: true
    repo: movesg/streamlit-docker-deployment
  name: streamlit-docker-deployment
